import type {Metadata} from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { FlareTrend } from "@/components/flare-chart";
import { NigeriaMap } from "@/components/map";
import { DataNote, Metric, SourceRail } from "@/components/ui";
import { flareSeries, getGeo, getMetadata } from "@/lib/data";
import { formatNumber, formatVolume, numberOrNull } from "@/lib/format";
import type { MapPoint } from "@/types/domain";
export const metadata:Metadata={title:"Flare cluster"};
export default async function ClusterPage({params}:{params:Promise<{name:string}>}){const {name}=await params;const cluster=decodeURIComponent(name);const [series,geo,metadata]=await Promise.all([flareSeries("cluster",cluster),getGeo("clusters"),getMetadata()]);if(!series.length)notFound();const latest=series.at(-1)!;const lat=numberOrNull(latest.y),lng=numberOrNull(latest.x);const point:MapPoint[]=lat!==null&&lng!==null?[{id:cluster,lat,lng,title:cluster,subtitle:`${formatVolume(latest.mscf)} · ${latest.month}`,kind:"flare"}]:[];const feature=geo.features.find(item=>String(item.properties.name??item.properties.Name??"").toLowerCase()===cluster.toLowerCase());const recent=series.slice(-12).map(row=>({month:String(row.month).slice(2),value:numberOrNull(row.mscf)??0}));const year2026=series.filter(row=>row.month?.startsWith("2026")).reduce((sum,row)=>sum+(numberOrNull(row.mscf)??0),0);return <><section className="detail-hero"><div className="container"><div className="breadcrumbs"><Link href="/gas-flares?area=cluster">Gas flares</Link> / Clusters / {cluster}</div><div className="detail-title"><div><span className="badge">Flare cluster</span><h1>{cluster}</h1><p>A tracker-defined cluster. It is not interchangeable with a state, LGA or oil block.</p></div></div></div></section><SourceRail label="Nigeria Gas Flare Tracker · cluster aggregation" observation={latest.month} retrieved={metadata.retrievedAt}/><div className="container page-pad"><div className="metric-grid" style={{marginBottom:22}}><Metric label="Latest observation" value={String(latest.month)} detail="Observation period"/><Metric label="Latest volume" value={formatVolume(latest.mscf)} detail="Tracker estimate"/><Metric label="2026 to latest" value={formatVolume(year2026)} detail="Jan through latest supplied month"/><Metric label="Months with values" value={formatNumber(series.length)} detail="Across tracker history"/></div><div className="split"><div className="panel"><div className="panel-head"><h2>Cluster location</h2></div><NigeriaMap points={point} polygons={feature?{type:"FeatureCollection",features:[feature]}:undefined} height={450} center={lat!==null&&lng!==null?[lat,lng]:[5.3,5.3]} zoom={10}/></div><div className="panel"><div className="panel-head"><h2>Monthly record</h2></div><div className="record-list">{series.slice(-8).reverse().map(row=><div className="record-row" key={String(row.month)}><time>{row.month}</time><div><strong>{formatVolume(row.mscf)}</strong><p>Detected flaring estimate</p></div><span className="status">Supplied</span></div>)}</div></div></div><div className="panel" style={{marginTop:22}}><div className="panel-head"><h2>Recent trend</h2></div><div className="panel-body"><FlareTrend data={recent}/></div></div><DataNote><strong>Cluster boundaries are tracker-defined.</strong> A cluster name and an oil block name describe different geographic systems, even when they overlap on a map.</DataNote></div></>}
