import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, BarChart3, Database, TableProperties } from "lucide-react";
import { CauseDistributionChart, CauseTrendChart } from "@/components/cause-analysis";
import { DataNote, SourceRail } from "@/components/ui";
import { getMetadata, getSpills } from "@/lib/data";
import { causeCategoryLabels, causeRecordDate, causeRecordHref, buildCauseAnalysis } from "@/lib/spill-causes";
import { formatDate, formatNumber, slugify } from "@/lib/format";
import { parseW3cDate } from "@/lib/sitemap-date";
import { siteUrl } from "@/lib/site";

const title = "Causes of Oil Spills in Nigeria: What Records Show";
const description = "Explore reported causes in Nigeria's public NOSDRA oil-spill records, with current source-snapshot trends, state patterns and links to underlying incidents.";

export async function generateMetadata({ searchParams }: { searchParams: Promise<{ year?: string }> }): Promise<Metadata> {
  const params = await searchParams;
  return {
    title, description,
    alternates: { canonical: "/oil-spills/causes" },
    robots: params.year ? { index: false, follow: true } : undefined,
    openGraph: { title, description, url: "/oil-spills/causes", type: "website" },
  };
}

function percent(value: number, total: number) {
  return total ? `${((value / total) * 100).toFixed(1)}%` : "0%";
}

function currentYear() {
  return new Date().getUTCFullYear().toString();
}

export default async function OilSpillCausesPage({ searchParams }: { searchParams: Promise<{ year?: string }> }) {
  const params = await searchParams;
  const [rows, sourceMetadata] = await Promise.all([getSpills(), getMetadata()]);
  const retrievedAt = parseW3cDate(sourceMetadata.retrievedAt);
  const analysis = buildCauseAnalysis(rows, retrievedAt, params.year);
  const years = analysis.years;
  const latestYear = years.at(-1) ?? "";
  const selected = analysis.selected;
  const selectedYear = selected.year ?? latestYear;
  const isCurrentPartialYear = selectedYear === currentYear();
  const snapshotDate = formatDate(sourceMetadata.retrievedAt.slice(0, 10));
  const national = analysis.national;
  const causeRows = national.categories;
  const selectedCauseRows = selected.categories;
  const faq = [
    { question: "What are the main reported causes of oil spills in Nigeria?", answer: "SpillFlare groups the cause values supplied in the current public source snapshot, including sabotage/theft, equipment failure, corrosion, operational/maintenance error, yet-to-determine entries and other source labels. The ranking describes source-record classifications, not independent findings of fault." },
    { question: "How does SpillFlare calculate oil-spill cause statistics?", answer: "Counts use indexable source records with a trusted incident date. The cause field is classified only when its source code or label matches the explicit mapping shown on this page; blank values remain missing." },
    { question: "Does reported cause mean SpillFlare verified the cause?", answer: "No. Cause values come from the underlying public records. SpillFlare summarizes those classifications and does not independently determine technical cause, fault or legal responsibility." },
    { question: "Why are some oil-spill causes missing or undetermined?", answer: "Some source records have no cause value, while others explicitly use the source's yet-to-determine code. Those cases are shown separately so the reported-cause distribution does not hide source incompleteness." },
    { question: "Can one SpillFlare record represent the same event as another record?", answer: "It can. One row is a source incident record and incident numbers are not guaranteed unique event identifiers. The page therefore reports record classifications rather than unique physical spill events." },
    { question: "Where does the cause data come from?", answer: "SpillFlare organizes public oil-spill records from the NOSDRA Oil Spill Monitor and links aggregate findings back to stable record pages where the supplied source fields can be inspected." },
  ];
  const structuredData = {
    "@context": "https://schema.org",
    "@graph": [
      { "@type": "CollectionPage", "@id": `${siteUrl}/oil-spills/causes#webpage`, url: `${siteUrl}/oil-spills/causes`, name: title, description, isPartOf: { "@id": `${siteUrl}/#website` }, about: { "@id": `${siteUrl}/oil-spills#dataset` }, mainEntity: { "@id": `${siteUrl}/oil-spills#dataset` } },
      { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: siteUrl }, { "@type": "ListItem", position: 2, name: "Oil spills", item: `${siteUrl}/oil-spills` }, { "@type": "ListItem", position: 3, name: "Reported causes", item: `${siteUrl}/oil-spills/causes` }] },
      { "@type": "FAQPage", mainEntity: faq.map((item) => ({ "@type": "Question", name: item.question, acceptedAnswer: { "@type": "Answer", text: item.answer } })) },
    ],
  };

  return <>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData).replace(/</g, "\\u003c") }} />
    <section className="analytics-hero"><div className="container"><div className="breadcrumbs"><Link href="/oil-spills">Oil spills</Link> / Reported causes</div><div className="analytics-hero-grid"><div><span className="eyebrow">NOSDRA source analysis</span><h1>Causes of Oil Spills in Nigeria: What the Public Records Show</h1><p>Explore the cause classifications recorded in Nigeria&apos;s public oil-spill records. SpillFlare summarizes source-record values using the current NOSDRA snapshot; it does not independently determine fault or legal responsibility.</p></div><div className="analytics-hero-actions"><Link className="button secondary" href="/oil-spills"><ArrowLeft size={16} />Incident explorer</Link></div></div></div></section>
    <SourceRail label="NOSDRA Oil Spill Monitor · reported-cause classifications" observation={sourceMetadata.sources.spillsPrimary.latestObservation} retrieved={sourceMetadata.retrievedAt} />
    <main className="wide-container analytics-page causes-page">
      <section className="analytics-intro panel" aria-label="Cause statistics scope"><div><span className="eyebrow">Current source snapshot</span><h2>How to read the cause statistics</h2><p>Snapshot retrieved {snapshotDate}. The analysis covers {formatNumber(national.consideredRecords)} indexable source records with trusted incident dates. One row is a source incident record, not necessarily an independently verified unique physical spill event.</p></div><div className="analytics-intro-links"><Link className="text-link" href="/oil-spills">Search all oil-spill records</Link><Link className="text-link" href="/oil-spills/analytics">Explore yearly statistics</Link><Link className="text-link" href="/data-and-methods">Read the data and methods</Link><Link className="text-link" href="/data-license">Review data reuse terms</Link></div></section>

      <section className="analytics-summary causes-summary" aria-label="Cause data coverage"><div><span>Trusted records considered</span><strong>{formatNumber(national.consideredRecords)}</strong><small>indexable source rows</small></div><div><span>Cause value supplied</span><strong>{formatNumber(national.populatedCause)}</strong><small>{percent(national.populatedCause, national.consideredRecords)} of considered records</small></div><div><span>Cause not supplied</span><strong>{formatNumber(national.missingCause)}</strong><small>{percent(national.missingCause, national.consideredRecords)} missing</small></div><div><span>Yet to determine</span><strong>{formatNumber(national.uncertainCause)}</strong><small>explicit source classification</small></div></section>
      <DataNote><strong>Cause values are taken from the underlying public source records.</strong> SpillFlare summarizes those classifications, but does not independently verify each cause or establish fault, liability or environmental impact.</DataNote>

      <section className="analytics-section" aria-labelledby="national-causes-heading"><div className="analytics-section-head"><div><span className="section-icon teal"><BarChart3 size={19} /></span><div><span className="eyebrow">National distribution</span><h2 id="national-causes-heading">Reported causes across the current records</h2><p>Percentages in the middle column use records with a populated cause field as the denominator. The final column uses all considered records.</p></div></div></div><div className="analytics-charts"><CauseDistributionChart data={causeRows} /><div className="table-wrap analytics-table-wrap"><table className="analytics-table causes-table"><caption>Reported cause classifications in the national source snapshot</caption><thead><tr><th>Displayed category</th><th className="numeric">Records</th><th className="numeric">Share with cause</th><th className="numeric">Share of all</th></tr></thead><tbody>{causeRows.map((item) => <tr key={item.category}><th scope="row">{item.label}</th><td className="numeric"><strong>{formatNumber(item.count)}</strong></td><td className="numeric">{item.category === "missing" ? "—" : percent(item.count, national.populatedCause)}</td><td className="numeric">{percent(item.count, national.consideredRecords)}</td></tr>)}</tbody></table></div></div><p className="analytics-footnote">“Cause not supplied” is kept visible and has no share-with-cause percentage because it is outside that denominator. “Yet to determine” is an explicit source value, not the same as a blank field.</p></section>

      <form className="analytics-toolbar" method="get"><div><TableProperties size={18} /><div><label htmlFor="causes-year">Analysis year</label><span>Update the cause tables and state patterns together</span></div></div><select id="causes-year" name="year" defaultValue={selectedYear}>{years.slice().reverse().map((year) => <option key={year} value={year}>{year}{year === currentYear() ? " · current snapshot" : ""}</option>)}</select><button className="button" type="submit">Update analysis</button></form>
      {isCurrentPartialYear && <DataNote><strong>{selectedYear} is an incomplete current-year snapshot.</strong> Its cause counts cover only records currently supplied by the source and should not be read as a completed calendar-year distribution.</DataNote>}

      <section className="analytics-section" aria-labelledby="selected-cause-heading"><div className="analytics-section-head"><div><span className="section-icon"><Database size={19} /></span><div><span className="eyebrow">Selected-year analysis</span><h2 id="selected-cause-heading">Reported causes in {selectedYear}</h2><p>{formatNumber(selected.consideredRecords)} trusted incident-date source records are in this year&apos;s view; {formatNumber(selected.populatedCause)} have a populated cause value.</p></div></div></div><div className="analytics-summary causes-selected-summary"><div><span>Records with cause value</span><strong>{formatNumber(selected.populatedCause)}</strong><small>{percent(selected.populatedCause, selected.consideredRecords)} of selected records</small></div><div><span>Cause not supplied</span><strong>{formatNumber(selected.missingCause)}</strong><small>{percent(selected.missingCause, selected.consideredRecords)} missing</small></div><div><span>Yet to determine</span><strong>{formatNumber(selected.uncertainCause)}</strong><small>explicit source value</small></div></div><div className="table-wrap analytics-table-wrap"><table className="analytics-table causes-table"><caption>{selectedYear} reported cause classifications</caption><thead><tr><th>Displayed category</th><th className="numeric">Records</th><th className="numeric">Share with cause</th></tr></thead><tbody>{selectedCauseRows.map((item) => <tr key={item.category}><th scope="row">{item.label}</th><td className="numeric"><strong>{formatNumber(item.count)}</strong></td><td className="numeric">{item.category === "missing" ? "—" : percent(item.count, selected.populatedCause)}</td></tr>)}</tbody></table></div></section>

      <section className="analytics-section" aria-labelledby="cause-trends-heading"><div className="analytics-section-head"><div><span className="section-icon teal"><BarChart3 size={19} /></span><div><span className="eyebrow">Trusted incident-year trends</span><h2 id="cause-trends-heading">How recorded cause classifications vary over time</h2><p>These are changes in source-record classifications. They are not automatically changes in real-world spill frequency or liability.</p></div></div></div><div className="analytics-charts"><CauseTrendChart data={analysis.yearly} /><div className="table-wrap analytics-table-wrap causes-trend-table-wrap"><table className="analytics-table causes-table causes-trend-table"><caption>Reported cause classifications by trusted incident year</caption><thead><tr><th>Year</th><th className="numeric">Total</th><th className="numeric">Sabotage / theft</th><th className="numeric">Equipment failure</th><th className="numeric">Corrosion</th><th className="numeric">Operational / maintenance</th><th className="numeric">Yet to determine</th><th className="numeric">Other</th><th className="numeric">Missing</th></tr></thead><tbody>{analysis.yearly.slice(-15).reverse().map((item) => <tr key={item.year}><th scope="row">{item.year}{item.year === currentYear() && <small className="current-year-note">Current snapshot</small>}</th><td className="numeric">{formatNumber(item.total)}</td><td className="numeric">{formatNumber(item.sabotage)}</td><td className="numeric">{formatNumber(item.equipment_failure)}</td><td className="numeric">{formatNumber(item.corrosion)}</td><td className="numeric">{formatNumber(item.operational)}</td><td className="numeric">{formatNumber(item.yet_to_be_determined)}</td><td className="numeric">{formatNumber(item.other)}</td><td className="numeric">{formatNumber(item.missing)}</td></tr>)}</tbody></table></div></div><p className="analytics-footnote"><strong>Current-year note:</strong> {currentYear()} values reflect the available source snapshot only and are not a completed calendar-year total.</p></section>

      <section className="analytics-section" aria-labelledby="state-pattern-heading"><div className="analytics-section-head"><div><span className="section-icon"><TableProperties size={19} /></span><div><span className="eyebrow">Geographic context</span><h2 id="state-pattern-heading">States represented in the selected cause records</h2><p>Counts use only explicit, resolvable source state fields. Location prose is not used to infer state membership.</p></div></div></div><div className="cause-state-grid">{selectedCauseRows.filter((item) => item.category !== "missing" && item.count > 0).map((item) => <div className="analytics-ranking-grid" key={item.category}><div><h3>{item.label}</h3><ol className="compact-ranking">{(selected.statesByCategory[item.category] ?? []).map((state) => <li key={state.name}><Link href={`/places/states/${slugify(state.name)}`}>{state.name}</Link><strong>{formatNumber(state.count)}</strong></li>)}</ol><p className="analytics-footnote">Source records in {selectedYear} with this reported-cause classification.</p></div></div>)}</div></section>

      <section className="analytics-section" aria-labelledby="labels-heading"><div className="analytics-section-head"><div><span className="section-icon"><TableProperties size={19} /></span><div><span className="eyebrow">Source-label transparency</span><h2 id="labels-heading">How cause labels are grouped</h2><p>The mapping is explicit and conservative; raw source labels remain available for audit.</p></div></div></div><div className="table-wrap analytics-table-wrap"><table className="analytics-table causes-table"><caption>Raw cause values and displayed categories</caption><thead><tr><th>Raw source label</th><th>Displayed category</th><th className="numeric">Records</th></tr></thead><tbody>{national.rawLabels.map((item) => { const category = Object.entries(causeCategoryLabels).find(([key]) => { const lower = item.label.toLowerCase(); return (key === "sabotage" && lower === "sab") || (key === "equipment_failure" && lower === "eqf") || (key === "corrosion" && lower === "cor") || (key === "operational" && lower === "ome") || (key === "yet_to_be_determined" && lower === "ytd") || (key === "other" && !["sab", "eqf", "cor", "ome", "ytd"].includes(lower)); })?.[0] ?? "other"; return <tr key={item.label}><th scope="row"><code>{item.label}</code></th><td>{causeCategoryLabels[category as keyof typeof causeCategoryLabels]}</td><td className="numeric">{formatNumber(item.count)}</td></tr>; })}</tbody></table></div><p className="analytics-footnote">Blank cause fields are counted separately as “Cause not supplied” and are not present in this populated-label table. No subjective merger of free-text “other:” values is applied.</p></section>

      <section className="analytics-section" aria-labelledby="records-heading"><div className="analytics-section-head"><div><span className="section-icon teal"><Database size={19} /></span><div><span className="eyebrow">Underlying evidence</span><h2 id="records-heading">Recent records by reported cause</h2><p>Open stable record pages to inspect the fields behind the selected-year summary.</p></div></div></div><div className="cause-record-grid">{selectedCauseRows.filter((item) => item.category !== "missing" && item.count > 0).map((item) => <div className="panel" key={item.category}><h3>{item.label}</h3><div className="analytics-record-list">{(selected.recentByCategory[item.category] ?? []).map((row) => <Link className="record-row" href={causeRecordHref(row)} key={row.id}><span><strong>{row.sitelocationname || "Location not supplied"}</strong><small>{row.company || "Operator not supplied"} · {row.incidentnumber || "Incident number not supplied"}</small></span><time>{causeRecordDate(row)}</time></Link>)}</div></div>)}</div></section>

      <section className="analytics-section authority-explainer" aria-labelledby="interpret-heading"><div className="card"><div className="card-icon"><Database size={21} /></div><h2 id="interpret-heading">What can these figures show?</h2><p>They show how the current source records classify reported causes, how those classifications are distributed and where records with each classification are represented. The source may reflect Joint Investigation Visit processes, later revisions or incomplete reporting.</p><p>They cannot independently establish technical correctness, legal responsibility, environmental severity, or whether two rows describe separate physical events.</p></div><div className="card"><div className="card-icon"><BarChart3 size={21} /></div><h2>What can cause an oil spill?</h2><p>{causeCategoryLabels.sabotage} entries preserve the source&apos;s sabotage/theft classification; equipment failure, corrosion and operational/maintenance error preserve the source&apos;s separate codes. “Other” values remain source-specific rather than being treated as a single proven mechanism.</p><p><Link className="text-link" href="/data-and-methods">Read the full source and date methodology</Link></p></div></section>

      <section className="analytics-section analytics-faq" aria-labelledby="faq-heading"><div className="analytics-section-head"><div><span className="section-icon teal"><TableProperties size={19} /></span><div><span className="eyebrow">Questions about cause data</span><h2 id="faq-heading">Nigeria oil-spill causes FAQ</h2></div></div></div><div className="faq">{faq.map((item) => <details key={item.question}><summary>{item.question}</summary><p>{item.answer}</p></details>)}</div></section>
    </main>
  </>;
}
